<homeGL>
	GridLayout:
		cols=3

		GridLayout:
			cols=1
			TextInput:
				text="New Answer Set"
				multiline=False
				size_hint_y=None
				height=50
			Button:
				text="Create"
			Label:
				text="Current Answer Sets"
		GridLayout:
			cols=1
			Button:
				text="Summarize"
			Button:
				text="Add New Answer Sheet"
			Button:
				text="Edit an Answer Sheet"
		GridLayout:
			cols=1
			Button:
				text="Done"